version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  phoenix:
    build: ./
    command:
      - ./run.sh
    volumes:
      - ./:/app:rw
    ports:
      - 4000:4000
    depends_on:
      - db
